steps:
- task: DownloadSecureFile@1
  name: idrsa
  displayName: 'Securely download id_rsa from Azure vault'
  inputs:
    secureFile: 'id_rsa'

- task: DownloadSecureFile@1
  name: netrc
  displayName: 'Securely download netrc from Azure vault'
  inputs:
    secureFile: 'netrc'
  
- script: |
    mv $(netrc.secureFilePath) ~/.netrc
    mkdir ~/.ssh
    sudo mv $(idrsa.secureFilePath) ~/.ssh/
    sudo chmod 400 ~/.ssh/id_rsa
  condition: ne( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Put secrets in their right places (non-Windows)'

- script: |
    echo '$(GOROOT)'
    echo '$(GOPATH)'
    echo '$(PATH)'
    echo '%PATH%'
    move $(netrc.secureFilePath) %USERPROFILE%\_netrc
    mkdir %USERPROFILE%\.ssh
    move $(idrsa.secureFilePath) %USERPROFILE%\.ssh\
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Put secrets in their right places (Windows)'
